### ISSUE TITLE
Expand README.md to include install guide

### ISSUE THREAD

**Issue by isabellabrookes** [PixelogicDev/Gruvee#10]
Noteworthy: 

- Node
- JDK 11 or lower
- Xcode
- iphone 11
- Android studio
- pixel 2 
- (npm script lists specific emulators)
- Cocoapods

**Comment by adilanchian** [comment]
This has been PUSHED. The README is currently in `release-1.0` and `song-comments`

Any sort of changes on this would be GREATLY appreciated :)
