### ISSUE TITLE
Github webhook with discord

### ISSUE THREAD

**Issue by isabellabrookes** [PixelogicDev/Gruvee#11]
I think this would be really cool:
https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks

post to #grüvee channel <3

**Comment by isabellabrookes** [comment]
FYI: "send me everything" for issues too

**Comment by BastianInuk** [comment]
Because I'm stupid; You're saying that github webhooks should post issues to #grüvee?

**Comment by isabellabrookes** [comment]
@BastianInuk yes, to both.

**Comment by adilanchian** [comment]
Added this! Hopefully this pushes an update :)
