### ISSUE TITLE
Not able to create Wiki

### ISSUE THREAD

**Issue by BastianInuk** [PixelogicDev/Gruvee#7]
I want to make and contribute to an FAQ for those dope green blocks on my GitHub profile, but couldn't.

**Comment by tjengland** [comment]
@BastianInuk any reason you don't want add details to README.md?

**Comment by adilanchian** [comment]
@BastianInuk - Try adding a Wiki now. I added permission to edit

**Comment by BastianInuk** [comment]
Thank you alec!

As for why not readme? It feels cleaner to seperate the concerns.
